# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Oct 28 13:23:06 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(846, 362)
        self.background = QtGui.QFrame(Dialog)
        self.background.setGeometry(QtCore.QRect(20, 20, 320, 320))
        self.background.setAutoFillBackground(True)
        self.background.setFrameShape(QtGui.QFrame.Box)
        self.background.setObjectName(_fromUtf8("background"))
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 20, 334, 321))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.left = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.left.setMinimum(0)
        self.left.setMaximum(640)
        self.left.setProperty("value", 0)
        self.left.setObjectName(_fromUtf8("left"))
        self.horizontalLayout_3.addWidget(self.left)
        self.top = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.top.setMinimum(0)
        self.top.setMaximum(640)
        self.top.setProperty("value", 0)
        self.top.setObjectName(_fromUtf8("top"))
        self.horizontalLayout_3.addWidget(self.top)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.right = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.right.setMinimum(0)
        self.right.setMaximum(640)
        self.right.setProperty("value", 0)
        self.right.setObjectName(_fromUtf8("right"))
        self.horizontalLayout_3.addWidget(self.right)
        self.bottom = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.bottom.setMinimum(0)
        self.bottom.setMaximum(640)
        self.bottom.setProperty("value", 0)
        self.bottom.setObjectName(_fromUtf8("bottom"))
        self.horizontalLayout_3.addWidget(self.bottom)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.type = QtGui.QComboBox(self.verticalLayoutWidget)
        self.type.setObjectName(_fromUtf8("type"))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.type)
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.textsize = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.textsize.setMinimum(1)
        self.textsize.setMaximum(320)
        self.textsize.setObjectName(_fromUtf8("textsize"))
        self.horizontalLayout_6.addWidget(self.textsize)
        spacerItem1 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.formLayout_2.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.description = QtGui.QPlainTextEdit(self.verticalLayoutWidget)
        self.description.setObjectName(_fromUtf8("description"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.description)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.textcolor = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.textcolor.setObjectName(_fromUtf8("textcolor"))
        self.horizontalLayout.addWidget(self.textcolor)
        self.labelcolor = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelcolor.setObjectName(_fromUtf8("labelcolor"))
        self.horizontalLayout.addWidget(self.labelcolor)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.listWidget = QtGui.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(350, 20, 131, 251))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.btndel = QtGui.QPushButton(Dialog)
        self.btndel.setGeometry(QtCore.QRect(370, 280, 86, 23))
        self.btndel.setObjectName(_fromUtf8("btndel"))
        self.btnadd = QtGui.QPushButton(Dialog)
        self.btnadd.setGeometry(QtCore.QRect(370, 310, 86, 23))
        self.btnadd.setObjectName(_fromUtf8("btnadd"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.left, self.top)
        Dialog.setTabOrder(self.top, self.right)
        Dialog.setTabOrder(self.right, self.bottom)
        Dialog.setTabOrder(self.bottom, self.type)
        Dialog.setTabOrder(self.type, self.textcolor)
        Dialog.setTabOrder(self.textcolor, self.textsize)
        Dialog.setTabOrder(self.textsize, self.description)
        Dialog.setTabOrder(self.description, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.listWidget)
        Dialog.setTabOrder(self.listWidget, self.btndel)
        Dialog.setTabOrder(self.btndel, self.btnadd)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "rect", None))
        self.label_5.setText(_translate("Dialog", "x", None))
        self.label_3.setText(_translate("Dialog", "type", None))
        self.type.setItemText(0, _translate("Dialog", "text", None))
        self.type.setItemText(1, _translate("Dialog", "image", None))
        self.type.setItemText(2, _translate("Dialog", "rating", None))
        self.type.setItemText(3, _translate("Dialog", "other", None))
        self.label_4.setText(_translate("Dialog", "text size", None))
        self.label_6.setText(_translate("Dialog", "description", None))
        self.label_7.setText(_translate("Dialog", "text color", None))
        self.labelcolor.setText(_translate("Dialog", "this is text color", None))
        self.pushButton_3.setText(_translate("Dialog", "save", None))
        self.pushButton_4.setText(_translate("Dialog", "export", None))
        self.btndel.setText(_translate("Dialog", "delete", None))
        self.btnadd.setText(_translate("Dialog", "add", None))

